### ISSUE TITLE
sprite.js does not honor scaleFactor

### ISSUE THREAD

**Issue by benloh** [daveseah/project-1401#2]
scaleFactor can be set in sprite.js, but sprite.js is not using it when rendering.

I think the relevant line is line 181:

			that.SetScaleXYZ(ww*that.scaleFactor,hh*that.scaleFactor,1*that.scaleFactor);

**Comment by daveseah** [comment]
Please provide a snippet of code to reproduce the behavior and describe what you expect to happen. Thanks!

**Comment by benloh** [comment]
In flowers.js, I expect to be able to set the size of a flower via a scale factor (e.g. 1.5 = 1 and a half times as large as normal).

So I insert line 249 in flower.js:

  			flowerPiece.Visual().SetZoom( spec.scale );

But without the change in sprite.js nothing happens.  The zoom is ignored.
Looking in sprite.js, the scaleFactor is not used to calculate anything.

Adding in the scaleFactor multiplication in sprite.js will then actually resize the sprites.

**Comment by daveseah** [comment]
Ok, will look into it! Thanks for the report! Maybe I should give you access to the 1401 project codebase as well.

**Comment by daveseah** [comment]
The suggested fix only works when the camera coordinate system is set to match the screen resolution, which isn't guaranteed to be the case. I can probably fix SetScaleXYZ to read the texture resolution and apply the unused scaleFactor every time it's called.

**Comment by daveseah** [comment]
NOTES

The size of a rendered sprite depends on the THREE.Object3D.scale property and the camera being used. The camera world can not be assumed to be based on pixel dimensions, but sprites require that their scale is set based on pixels. That is the confusing part.

* THREE.sprite.scale is set to the pixel dimensions of the displayed portion of the sprite. For a 32x32 single texture sprite, scale.x and scale.y are set to 32. For a spritesheet of 64x32 with 2 sprites, the scale.x and scale.y are still 32.  
* Textures are loaded *asynchronously*, so the dimensions of the texture aren't available at sprite creation time. This is accessed through `sprite.material.image.width` and `.height` once the texture is loaded.
* Once a texture is loaded through Three's loadTexture() call, the onload handler is called just once per texture path loaded. 
* The "zoom factor" is a concept that's added by InqSprite (built on THREE.Sprite), allowing a scale factor to be applied. It has to be applied to the current sprite scale, which is in pixel dimensions but may not match the material.image.width/height properties (in the case of spritesheets).

**Comment by daveseah** [comment]
Commit 2aeb6438 fixes this.
