### ISSUE TITLE
sprite.js: ScaleXYZ method uses nonexistent "scale" variable

### ISSUE THREAD

**Issue by benloh** [daveseah/project-1401#3]
Line 212.

Javascript throws an error if the ScaleXYZ method is called because "scale" is undefined.

Line 213 should probably be:

		return { x: this.scale.x, y:  this.scale.y, z:  this.scale.z }; // for threeJS scaling

**Comment by daveseah** [comment]
Congratulations, you are the first person ever to use this call! :) Applying fix.

**Comment by daveseah** [comment]
Commit dfeb8c6 addresses this and issue #2
